caldron1 = "    .-_-.   "
caldron2 = "   /_ _  \  "
caldron3 = "   \@ @  /  "
caldron4 = "   (_> _)   "
caldron5 = "    `)(_    "
caldron6 = "    /((_`)_,"
caldron7 = "    \__(/-  "
caldron8 = "     |||    "
caldron9 = "  ((__|__)) "
caldron10 = ""
caldron11 = "jgs        "
caldron12 = ""

merlin1 ="                __        _      "
merlin2 ="              _/  \    _(\(o     "
merlin3 ="             /     \  /  _  ^^^o "
merlin4 ="            /   !   \/  ! '!!!v' "
merlin5 ="           !  !  \ _' ( \____    "
merlin6 ="           ! . \ _!\   \===^\)   "
merlin7 ="Art by      \ \_!  / __!         "
merlin8 =" Gunnar Z.   \!   /    \         "
merlin9 ="       (\_      _/   _\ )        "
merlin10="        \ ^^--^^ __-^ /(__       "
merlin11="         ^^----^^    ^--v"
merlin12=""